### ISSUE TITLE
Mistake in Readme

### ISSUE THREAD

**Issue by carlosmojopicon** [NikolaiRadke/JQ6500-rescue-tool#2]
I think there's an error in your instructions, where it says:
`./jq6500 -o -r 0 JQ6500_iso/ISO_8Mbit/MusicDownload.iso for 8MBit modules or
./jq6500 -o -r 0 JQ6500_iso/ISO_16Mbit/MusicDownload.iso for 16MBit modules or
./jq6500 -o -r 0 JQ6500_iso/ISO_32MBit/MusicDownload.iso for 32MBit modules or
./jq6500 -o -r 0 JQ6500_iso/ISO_64Mbit/MusicDownload.iso for 64MBit modules or
./jq6500 -o -r 0 JQ6500_iso/ISO_128Mbit/MusicDownload.iso for 128MBit modules.`

it should say:
`./jq6500 -o 0 -r JQ6500_iso/ISO_8Mbit/MusicDownload.iso for 8MBit modules or
./jq6500 -o 0 -r JQ6500_iso/ISO_16Mbit/MusicDownload.iso for 16MBit modules or
./jq6500 -o 0 -r JQ6500_iso/ISO_32MBit/MusicDownload.iso for 32MBit modules or
./jq6500 -o 0 -r JQ6500_iso/ISO_64Mbit/MusicDownload.iso for 64MBit modules or
./jq6500 -o 0 -r JQ6500_iso/ISO_128Mbit/MusicDownload.iso for 128MBit modules.`

**Comment by NikolaiRadke** [comment]
Hi!
Thanks for your message and sorry for the late reply.
Yes, you are certainly right. i messed up the order.

Anyway, this repo needs a rework with more tutorials. I hope i will have more free time in december.

My regarts,

Nikolai
