### ISSUE TITLE
little typo in readme and big thanks!

### ISSUE THREAD

**Issue by DDDanny** [NikolaiRadke/JQ6500-rescue-tool#3]
Dear Nokilai,

regarding readme:
"8. Plug in your device again and enjoy the funny Chinese intera_c_e :-) Congrats, your module is usable again."
Just feel free to update on your next commit

Beside of this, a real big thanks - i failed first on my very old 32bit vario notebook - but it worked like a charm and straight forward on a 64bit cpu

BIG THANKS!

Keep on man and best wishes from Hamburg
Danny

**Comment by NikolaiRadke** [comment]
Dear Danny,

thanks for bugfix and especially  the hint! Indeed, the tool is compiled for x86_64Bit CPUs. i added this information. A 32Bit version will follow in December. 

Best wishes from Berlin!
Nikolai
