### ISSUE TITLE
JQ6500 and minimal aren't copied over.

### ISSUE THREAD

**Issue by feldon30** [NikolaiRadke/JQ6500-rescue-tool#4]
Possibly user error, but I flashed jq6500_rescue_linux.iso to a FAT32 thumb drive with Unetbootin and other than Minimal Linux Live, there is nothing else on the boot partition. jq6500 is absent. There is no prompt to setup the jq6500 by pressing "r" as indicated in the instructions.  It's just a plain vanilla Minimal Linux Live boot.

**Comment by NikolaiRadke** [comment]
Hello,
alas, I checked this issue and you are right: Unetbootin is unable to copy the image the right way. I don't know why, I certainly checked Unetbootin for a while.

I recommend using Rufus:
https://rufus.ie/
You can download the newest fresh tested version here:
https://github.com/pbatard/rufus/releases/download/v3.8/rufus-3.8.exe

Rufus will ask you after clicking "Start" if you want to choose "ISO image mode" or "dd image mode". Choose "dd image mode" (dd = disk dump, a common linux tool for bit wise copying files) and it should work.

Thanks for your message, I will edit the Readme.

**Comment by NikolaiRadke** [comment]
Would you please write me your experience?

**Comment by feldon30** [comment]
Thank you kindly for the detailed response and suggested solution. I thought I was going crazy. :)
